
/** Hier werden alle Fragen und die Antworten gespeichert. Format: JSON */
let questions = [
    {
        "question": "Wie bezeichnet man Down Syndrom noch?",
        "answer_1": "Trisomie 21",
        "answer_2": "Chromosom",
        "answer_3": "Trisome 22",
        "answer_4": "Chromosom 22",
        "right answer": 1,
    },
    {
        "question": "Welche frühere Bezeichnung für Trisomie 21 wurde abgeschafft, da sie diskriminierend war?",
        "answer_1": "Mangolismus",
        "answer_2": "Mongolis",
        "answer_3": "Mongolismus",
        "answer_4": "Mangolismus",
        "right answer": 3,
    },
    {
        "question": "Was ist ein Gen?",
        "answer_1": "Ein Bauplan eines Lebenwesens.",
        "answer_2": "Ein Bauplan für ein Haus.",
        "answer_3": "Haben nur Tiere.",
        "answer_4": "Haben nur Menschen.",
        "right answer": 1,
    },
    {
        "question": "Viele Gene bilden eine Art Fäden...",
        "answer_1": "Google Chrome",
        "answer_2": "Genom",
        "answer_3": "Chromotomen",
        "answer_4": "Chromosomen",
        "right answer": 4,
    },
    {
        "question": "Was ist das Genom eines Lebewesens?",
        "answer_1": "Alle Gene gemeinsam bilden das Genom eines Lebewesens.",
        "answer_2": "Ein Gen ist auch ein Genom.",
        "answer_3": "Alle Gene im Gehirn sind das Genom.",
        "answer_4": "Das Genom ist das, was ein Lebewesen im Kopf hat.",
        "right answer": 1,
    },
    {
        "question": "Was ist eine RNA?",
        "answer_1": "Anderer Name für die DNA.",
        "answer_2": "Zwischenspeicher der Information.",
        "answer_3": "Boh, gute Frage.",
        "answer_4": "Rascher neutraler Ansatz.",
        "right answer": 2,
    },
    {
        "question": "Die Gene geben also vor,...",
        "answer_1": "Wie schnell der Mensch gehen kann.",
        "answer_2": "Wie sich das Wetter verändert.",
        "answer_3": "Wie sich der Mensch bewegt.",
        "answer_4": "Wie sich der Körper entwickelt.",
        "right answer": 4,
    },
    {
        "question": "Wieso hat ein Kind z.B. die Augenfarbe des Vaters und die Haarfarbe der Mutter?",
        "answer_1": "Weil sich die Eltern nicht entscheiden konnten.",
        "answer_2": "Die DNA wurde in einem Labor mutiert",
        "answer_3": "Bei der Fortpflanzung haben sich die Gene von Mutter und Vater gemischt.",
        "answer_4": "Das ist Zufall, da gibt es keine wissenschaftliche Erklärung dafür.",
        "right answer": 3,
    },
    {
        "question": "Wie viele Chromosomen stecken in Körperzellen eines Mensches?",
        "answer_1": "48",
        "answer_2": "69",
        "answer_3": "46",
        "answer_4": "59",
        "right answer": 3,
    },
    {
        "question": "Was ist die Trisonomie 21?",
        "answer_1": "Syndrom-Abc",
        "answer_2": "Don-Syndrom",
        "answer_3": "Krebs",
        "answer_4": "Down-Syndrom",
        "right answer": 4,
    }
];