
/** Hier werden alle Fragen und die Antworten gespeichert. Format: JSON */
let genetics = [
    {
        "question": "Wie bezeichnet man Down Syndrom noch?",
        "answer_1": "Trisomie 21",
        "answer_2": "Chromosom",
        "answer_3": "Trisome 22",
        "answer_4": "Chromosom 22",
        "right answer": 1,
    },
    {
        "question": "Welche frühere Bezeichnung für Trisomie 21 wurde abgeschafft, da sie diskriminierend war?",
        "answer_1": "Mangolismus",
        "answer_2": "Mongolis",
        "answer_3": "Mongolismus",
        "answer_4": "Mangolismus",
        "right answer": 3,
    },
    {
        "question": "Was ist ein Gen?",
        "answer_1": "Ein Bauplan eines Lebenwesens.",
        "answer_2": "Ein Bauplan für ein Haus.",
        "answer_3": "Haben nur Tiere.",
        "answer_4": "Haben nur Menschen.",
        "right answer": 1,
    },
    {
        "question": "Viele Gene bilden eine Art Fäden...",
        "answer_1": "Google Chrome",
        "answer_2": "Genom",
        "answer_3": "Chromotomen",
        "answer_4": "Chromosomen",
        "right answer": 4,
    },
    {
        "question": "Was ist das Genom eines Lebewesens?",
        "answer_1": "Alle Gene gemeinsam bilden das Genom eines Lebewesens.",
        "answer_2": "Ein Gen ist auch ein Genom.",
        "answer_3": "Alle Gene im Gehirn sind das Genom.",
        "answer_4": "Das Genom ist das, was ein Lebewesen im Kopf hat.",
        "right answer": 1,
    },
    {
        "question": "Was ist eine RNA?",
        "answer_1": "Anderer Name für die DNA.",
        "answer_2": "Zwischenspeicher der Information.",
        "answer_3": "Boh, gute Frage.",
        "answer_4": "Rascher neutraler Ansatz.",
        "right answer": 2,
    },
    {
        "question": "Die Gene geben also vor,...",
        "answer_1": "Wie schnell der Mensch gehen kann.",
        "answer_2": "Wie sich das Wetter verändert.",
        "answer_3": "Wie sich der Mensch bewegt.",
        "answer_4": "Wie sich der Körper entwickelt.",
        "right answer": 4,
    },
    {
        "question": "Wieso hat ein Kind z.B. die Augenfarbe des Vaters und die Haarfarbe der Mutter?",
        "answer_1": "Weil sich die Eltern nicht entscheiden konnten.",
        "answer_2": "Die DNA wurde in einem Labor mutiert",
        "answer_3": "Bei der Fortpflanzung haben sich die Gene von Mutter und Vater gemischt.",
        "answer_4": "Das ist Zufall, da gibt es keine wissenschaftliche Erklärung dafür.",
        "right answer": 3,
    },
    {
        "question": "Wie viele Chromosomen stecken in Körperzellen eines Mensches?",
        "answer_1": "48",
        "answer_2": "69",
        "answer_3": "46",
        "answer_4": "59",
        "right answer": 3,
    },
    {
        "question": "Was ist die Trisonomie 21?",
        "answer_1": "Syndrom-Abc",
        "answer_2": "Don-Syndrom",
        "answer_3": "Krebs",
        "answer_4": "Down-Syndrom",
        "right answer": 4,
    }
];


let proportionality = [
    {
        "question": "In der direkten Proportionalität werden beide Seiten in der Wertetabelle...",
        "answer_1": "durch dieselbe Zahl dividiert oder multipliziert.",
        "answer_2": "durch dieselbe Zahl dividiert oder addiert.",
        "answer_3": "durch dieselbe Zahl multipliziert oder addiert.",
        "answer_4": "durch dieselbe Zahl Subtrahiert oder addiert.",
        "right answer": 1,
    },
    {
        "question": "In der indirekten Proportionalität ... man die Ausgangsgröße mit der zugeordneten Größe - so ist das Produkt immer gleich.",
        "answer_1": "addiert",
        "answer_2": "multipliziert",
        "answer_3": "subtrahiert",
        "answer_4": "dividiert",
        "right answer": 2,
    },
    {
        "question": "Die Kurve in der indirekten Proportionalität man auch:",
        "answer_1": "Inskriptionen.",
        "answer_2": "Schenkel.",
        "answer_3": "Graph.",
        "answer_4": "Hyperbel.",
        "right answer": 4,
    },
    {
        "question": "Je mehr Schokolade man kauft,...  ",
        "answer_1": "desto weniger muss man bezahlen.",
        "answer_2": "muss man gleich viel zahlen.",
        "answer_3": "desto mehr muss man bezahlen.",
        "answer_4": "desto unterschiedlicher muss man bezahlen.",
        "right answer": 3,
    },
    {
        "question": "Auf beiden Seiten der Wertetabelle wird...",
        "answer_1": "durch dieselbe Zahl dividiert.",
        "answer_2": "durch eine andere Zahl dividiert.",
        "answer_3": "durch eine unterschiedliche Zahl dividiert.",
        "answer_4": "durch sich selbst dividiert.",
        "right answer": 1,
    },
    {
        "question": "Was gilt für die direkte Proportionalität?",
        "answer_1": "keine von diesen",
        "answer_2": "Je mehr.., desto mehr..",
        "answer_3": "Je mehr.., desto weniger..",
        "answer_4": "Je weniger.., desto mehr..",
        "right answer": 2,
    },
    {
        "question": "Was gilt für die indirekte Proportionalität?",
        "answer_1": "Je mehr.., desto mehr..",
        "answer_2": "Je weniger.., desto weniger..",
        "answer_3": "Keine Ahnung ",
        "answer_4": "Je mehr.., desto weniger..",
        "right answer": 4,
    },
    {
        "question": "Ein Arbeiter braucht 6 Tage um ein Haus zu bauen. Wieviel brauchen drei Arbeiter?",
        "answer_1": "2 Tage",
        "answer_2": "3 Tage",
        "answer_3": "4 Tage",
        "answer_4": "5 Tage",
        "right answer": 1,
    },
    {
        "question": "4 Gärtner brauchen 12 Tage um den Platz zu gestalten. Wieviel Tage braucht ein Gärtner?",
        "answer_1": "14 Tage",
        "answer_2": "32 Tage",
        "answer_3": "50 Tage",
        "answer_4": "48 Tage",
        "right answer": 4,
    },
    {
        "question": "Wenn 12 Pizzen 6 € kosten, wie viel kostet dann 1 Pizza?",
        "answer_1": "5 €",
        "answer_2": "1 ct",
        "answer_3": "50 ct",
        "answer_4": "2 €",
        "right answer": 3,
    },
    {
        "question": "Je größer die Anzahl der Fitnessgeräte im Haushalt ist, desto größer ist Fitness der Familie.     ",
        "answer_1": "direkte Proportionalität",
        "answer_2": "indirekte Proportionalität",
        "answer_3": "nichts von beidem",
        "answer_4": "beides",
        "right answer": 3,
    },
    {
        "question": "Je größer die Anzahl der gekauften Harry Potter Bücher ist, desto größer ist der Gesamtpreis. Annahme: Alle Bücher kosten gleich viel.",
        "answer_1": "direkte Proportionalität",
        "answer_2": "indirekte Proportionalität",
        "answer_3": "nichts von beidem",
        "answer_4": "beides",
        "right answer": 1,
    },
    {
        "question": "Für die direkte Proportionalität gilt......?",
        "answer_1": "Je mehr....,desto mehr... & Je weniger...,desto weniger...",
        "answer_2": "Je flüssiger...., desto flüssiger... & Je härter..., desto härter...",
        "answer_3": "Je fetter...., desto fetter... & Je dünner..., desto dünner...  ",
        "answer_4": "Je dümmer...., desto dümmer... & Je winziger..., desto winziger...",
        "right answer": 1,
    },
    {
        "question": "Für die indirekte Proportionalität gilt:",
        "answer_1": "Je mehr, desto weniger.",
        "answer_2": "Je mehr, desto mehr.",
        "answer_3": "Je weniger, desto weniger.",
        "answer_4": "Je weniger, desto besser.",
        "right answer": 1,
    },
];


let percentCalculation = [
    {
        "question": "Was gibt der Grundwert an?",
        "answer_1": "Gesamtwert",
        "answer_2": "Prozentwert",
        "answer_3": "Rabbat Wert",
        "answer_4": "Prozentsatz",
        "right answer": 1,
    },
    {
        "question": "was sind 50%?",
        "answer_1": "¼",
        "answer_2": "⅚",
        "answer_3": "½",
        "answer_4": "⅞",
        "right answer": 3,
    },
    {
        "question": "was sind 10% von 180?",
        "answer_1": "20",
        "answer_2": "30",
        "answer_3": "0",
        "answer_4": "18",
        "right answer": 4,
    },
    {
        "question": "Barbara hat beim Deutschdiktat 8% aller Wörter falsch geschrieben, das sind 20 Wörter. Was wird hier gesucht?",
        "answer_1": "Prozentwert",
        "answer_2": "Proportionalität",
        "answer_3": "Prozentsatz",
        "answer_4": "Grundwert",
        "right answer": 4,
    },
    {
        "question": "Von den 340 Kindern einer Schule gehen 45% täglich zu Fuß zur Schule. Was wird hier gesucht?",
        "answer_1": "Grundwert",
        "answer_2": "Prozentsatz",
        "answer_3": "Prozentwert",
        "answer_4": "Proportionalität",
        "right answer": 1,
    },
    {
        "question": "Wie viel Prozent ist die Hälfte von der Hälfte?",
        "answer_1": "50%",
        "answer_2": "0%",
        "answer_3": "10%",
        "answer_4": "25%",
        "right answer": 4,
    },
    {
        "question": "2% von 600 cm",
        "answer_1": "110 mm",
        "answer_2": "16 cm",
        "answer_3": "12 cm",
        "answer_4": "11 cm",
        "right answer": 3,
    },
    {
        "question": "Was gibt der Prozentsatz an?",
        "answer_1": "Anteil von der Hälfte in Prozent.",
        "answer_2": "Den Anteil vom Ganzen in Prozent.",
        "answer_3": "Das Wetter.",
        "answer_4": "Den Prozentwert in Sätzen.",
        "right answer": 2,
    },
    {
        "question": "Berechne den Prozentwert  p%: 10%  Grundwert: 300  W:?",
        "answer_1": "45",
        "answer_2": "30",
        "answer_3": "28",
        "answer_4": "49",
        "right answer": 2,
    },
    {
        "question": "Jonas hat 32 Kekse. Er isst 24 davon. Was hat er in Prozent?",
        "answer_1": "75%",
        "answer_2": "10%",
        "answer_3": "47%",
        "answer_4": "Diabetis 20 %",
        "right answer": 1,
    },
    {
        "question": "Brigitte hat 126€. Sie kauft eine Tasche, die die Hälfte kostet. Wie viel kostet die Tasche?",
        "answer_1": "75 €",
        "answer_2": "88 €",
        "answer_3": "63 €",
        "answer_4": "65 €",
        "right answer": 3,
    },
    {
        "question": "Wie viel sind 10% von 100?",
        "answer_1": "6000",
        "answer_2": "10",
        "answer_3": "40",
        "answer_4": "400",
        "right answer": 2,
    },
];


let circle = [
    {
        "question": "Wie viele Ecken hat ein Kreis?",
        "answer_1": "0",
        "answer_2": "1",
        "answer_3": "2",
        "answer_4": "3",
        "right answer": 1,
    },
    {
        "question": "Die Zahl Pi...",
        "answer_1": "Ist auch mit einem Bruch darstellbar.",
        "answer_2": "Beträgt 3,1424...",
        "answer_3": "Hat unendlich viele Nachkommastellen.",
        "answer_4": "Ist eine moderne Sage, es gibt sie nicht",
        "right answer": 3,
    },
    {
        "question": "Den Umfang eines Kreises berechnet man mit:",
        "answer_1": "Radius mal Radius mal Pi.",
        "answer_2": "Durchmesser mal Pi.",
        "answer_3": "Dazu gibt es keine Rechnung, man kann nur messen.",
        "answer_4": "Radius mal Durchmesser mal Pi",
        "right answer": 2,
    },
];